import type { Metadata } from "next";
import localFont from "next/font/local";
import { Playfair_Display } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { AuthProvider } from "@/components/providers/auth-provider";
import { cn } from "@/lib/utils";

const ceraPro = localFont({
  src: [
    // Thin

    {
      path: "../assets/fonts/cera-pro-font/cerapro-thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../assets/fonts/cera-pro-font/cerapro-thinitalic.otf",
      weight: "100",
      style: "italic",
    },

    // Light
    {
      path: "../assets/fonts/cera-pro-font/cerapro-light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../assets/fonts/cera-pro-font/cerapro-lightitalic.otf",
      weight: "300",
      style: "italic",
    },

    // Regular
    {
      path: "../assets/fonts/cera-pro-font/cerapro-regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/cera-pro-font/cerapro-regularitalic.otf",
      weight: "400",
      style: "italic",
    },

    // Medium
    {
      path: "../assets/fonts/cera-pro-font/cerapro-medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/cera-pro-font/cerapro-mediumitalic.otf",
      weight: "500",
      style: "italic",
    },

    // Bold
    {
      path: "../assets/fonts/cera-pro-font/cerapro-bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assets/fonts/cera-pro-font/cerapro-bolditalic.otf",
      weight: "700",
      style: "italic",
    },

    // Black
    {
      path: "../assets/fonts/cera-pro-font/cerapro-black.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../assets/fonts/cera-pro-font/cerapro-blackitalic.otf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-cera-pro",
  display: "swap",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],

  style: ["normal", "italic"],
  variable: "--font-display",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(ceraPro.variable, playfairDisplay.variable)}
      suppressHydrationWarning
    >
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            {children}
            <Toaster />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
