import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { AuthProvider } from "@/components/providers/auth-provider";
import { cn } from "@/lib/utils";

const ceraPro = localFont({
  src: [
    // Thin

    {
      path: "../assets/fonts/cera-pro-font/CeraProThin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../assets/fonts/cera-pro-font/CeraProThinItalic.otf",
      weight: "100",
      style: "italic",
    },

    // Light
    {
      path: "../assets/fonts/cera-pro-font/CeraProLight.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../assets/fonts/cera-pro-font/CeraProLightItalic.otf",
      weight: "300",
      style: "italic",
    },

    // Regular
    {
      path: "../assets/fonts/cera-pro-font/CeraProRegular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/cera-pro-font/CeraProRegularItalic.otf",
      weight: "400",
      style: "italic",
    },

    // Medium
    {
      path: "../assets/fonts/cera-pro-font/CeraProMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/cera-pro-font/CeraProMediumItalic.otf",
      weight: "500",
      style: "italic",
    },

    // Bold
    {
      path: "../assets/fonts/cera-pro-font/CeraProBold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assets/fonts/cera-pro-font/CeraProBoldItalic.otf",
      weight: "700",
      style: "italic",
    },

    // Black
    {
      path: "../assets/fonts/cera-pro-font/CeraProBlack.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../assets/fonts/cera-pro-font/CeraProBlackItalic.otf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-cera-pro",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(ceraPro.variable)} suppressHydrationWarning>
      <body className={`antialiased hide-scrollbar `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            {children}
            <Toaster />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
